development:
  adapter: mysql2
  encoding: utf8
  database: rails101_development
  host: localhost
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  database: rails101_test
  host: localhost
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  database: rails101_production
  host: localhost
  username: root
  password: 